; ============================================================
; level.h — generated by EXLCHAR v11 LEVEL EDITOR
; 40 cols × 25 rows — full screen
; Tile count: 36 tiles, 2 stamps
; ============================================================

; Tile definitions (char code, attr, solid)
TILE_EMPTY    .equ    0   ; char=$7F attr=$10
TILE_FLOOR    .equ    1   ; char=$50 attr=$F0 SOLID
TILE_WALL    .equ    2   ; char=$51 attr=$F0 SOLID
TILE_CEIL    .equ    3   ; char=$52 attr=$F0 SOLID
TILE_STONE_WALL_10    .equ    4   ; char=$10 attr=$F8
TILE_STONE_WALL_11    .equ    5   ; char=$11 attr=$F8
TILE_STONE_WALL_12    .equ    6   ; char=$12 attr=$F8
TILE_STONE_WALL_13    .equ    7   ; char=$13 attr=$F8
TILE_STONE_WALL_14    .equ    8   ; char=$14 attr=$F8
TILE_STONE_WALL_15    .equ    9   ; char=$15 attr=$F8
TILE_STONE_WALL_16    .equ    10   ; char=$16 attr=$F8
TILE_STONE_WALL_17    .equ    11   ; char=$17 attr=$F8
TILE_STONE_WALL_18    .equ    12   ; char=$18 attr=$F8
TILE_STONE_WALL_19    .equ    13   ; char=$19 attr=$F8
TILE_STONE_WALL_1A    .equ    14   ; char=$1A attr=$F8
TILE_STONE_WALL_1B    .equ    15   ; char=$1B attr=$F8
TILE_STONE_WALL_1C    .equ    16   ; char=$1C attr=$F8
TILE_STONE_WALL_1D    .equ    17   ; char=$1D attr=$F8
TILE_STONE_WALL_1E    .equ    18   ; char=$1E attr=$F8
TILE_STONE_WALL_1F    .equ    19   ; char=$1F attr=$F8
TILE_STONE_WALL_21    .equ    20   ; char=$21 attr=$F8
TILE_STONE_WALL_22    .equ    21   ; char=$22 attr=$F8
TILE_STONE_WALL_23    .equ    22   ; char=$23 attr=$F8
TILE_STONE_WALL_24    .equ    23   ; char=$24 attr=$F8
TILE_STONE_WALL_25    .equ    24   ; char=$25 attr=$F8
TILE_STONE_WALL_26    .equ    25   ; char=$26 attr=$F8
TILE_STONE_WALL_27    .equ    26   ; char=$27 attr=$F8
TILE_STONE_WALL_28    .equ    27   ; char=$28 attr=$F8
TILE_STONE_WALL_29    .equ    28   ; char=$29 attr=$F8
TILE_STONE_WALL_2A    .equ    29   ; char=$2A attr=$F8
TILE_STONE_WALL_2B    .equ    30   ; char=$2B attr=$F8
TILE_STONE_WALL_2C    .equ    31   ; char=$2C attr=$F8
TILE_STONE_WALL_2D    .equ    32   ; char=$2D attr=$F8
TILE_STONE_WALL_2E    .equ    33   ; char=$2E attr=$F8
TILE_STONE_WALL_2F    .equ    34   ; char=$2F attr=$F8
TILE_STONE_WALL_30    .equ    35   ; char=$30 attr=$F8

; Tile char/attr lookup table (2 bytes per tile: attr, char)
TILE_CHARS:
        .byte   $10,$7F   ; EMPTY
        .byte   $F0,$50   ; FLOOR SOLID
        .byte   $F0,$51   ; WALL SOLID
        .byte   $F0,$52   ; CEIL SOLID
        .byte   $F8,$10   ; STONE_WALL_10
        .byte   $F8,$11   ; STONE_WALL_11
        .byte   $F8,$12   ; STONE_WALL_12
        .byte   $F8,$13   ; STONE_WALL_13
        .byte   $F8,$14   ; STONE_WALL_14
        .byte   $F8,$15   ; STONE_WALL_15
        .byte   $F8,$16   ; STONE_WALL_16
        .byte   $F8,$17   ; STONE_WALL_17
        .byte   $F8,$18   ; STONE_WALL_18
        .byte   $F8,$19   ; STONE_WALL_19
        .byte   $F8,$1A   ; STONE_WALL_1A
        .byte   $F8,$1B   ; STONE_WALL_1B
        .byte   $F8,$1C   ; STONE_WALL_1C
        .byte   $F8,$1D   ; STONE_WALL_1D
        .byte   $F8,$1E   ; STONE_WALL_1E
        .byte   $F8,$1F   ; STONE_WALL_1F
        .byte   $F8,$21   ; STONE_WALL_21
        .byte   $F8,$22   ; STONE_WALL_22
        .byte   $F8,$23   ; STONE_WALL_23
        .byte   $F8,$24   ; STONE_WALL_24
        .byte   $F8,$25   ; STONE_WALL_25
        .byte   $F8,$26   ; STONE_WALL_26
        .byte   $F8,$27   ; STONE_WALL_27
        .byte   $F8,$28   ; STONE_WALL_28
        .byte   $F8,$29   ; STONE_WALL_29
        .byte   $F8,$2A   ; STONE_WALL_2A
        .byte   $F8,$2B   ; STONE_WALL_2B
        .byte   $F8,$2C   ; STONE_WALL_2C
        .byte   $F8,$2D   ; STONE_WALL_2D
        .byte   $F8,$2E   ; STONE_WALL_2E
        .byte   $F8,$2F   ; STONE_WALL_2F
        .byte   $F8,$30   ; STONE_WALL_30

; Solid tile flags (1=solid, 0=passable)
TILE_SOLID:
        .byte   0,1,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0

TILE_COUNT  .equ    36

; Level grid — one byte per cell (0=EMPTY, 1=FLOOR, etc., $FF=empty/air)
LEVEL_MAP:
        .byte   $FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF ; row 0
        .byte   $FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF ; row 1
        .byte   $04,$05,$06,$07,$08,$09,$04,$05,$06,$07,$08,$09,$04,$05,$06,$07,$08,$09,$04,$05,$06,$07,$08,$09,$04,$05,$06,$07,$08,$09,$04,$05,$06,$07,$08,$09,$04,$05,$06,$07 ; row 2
        .byte   $0A,$0B,$0C,$0D,$0E,$0F,$0A,$0B,$0C,$0D,$0E,$0F,$0A,$0B,$0C,$0D,$0E,$0F,$0A,$0B,$0C,$0D,$0E,$0F,$0A,$0B,$0C,$0D,$0E,$0F,$0A,$0B,$0C,$0D,$0E,$0F,$0A,$0B,$0C,$0D ; row 3
        .byte   $10,$11,$12,$13,$14,$15,$10,$11,$12,$13,$14,$15,$10,$11,$12,$13,$14,$15,$10,$11,$12,$13,$14,$15,$10,$11,$12,$13,$14,$15,$10,$11,$12,$13,$14,$15,$10,$11,$12,$13 ; row 4
        .byte   $FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF ; row 5
        .byte   $FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF ; row 6
        .byte   $FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF ; row 7
        .byte   $FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF ; row 8
        .byte   $FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF ; row 9
        .byte   $FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF ; row 10
        .byte   $FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF ; row 11
        .byte   $FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF ; row 12
        .byte   $FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$00,$00,$FF,$FF,$00,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF ; row 13
        .byte   $00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00 ; row 14
        .byte   $04,$05,$06,$07,$08,$09,$04,$05,$06,$07,$08,$09,$04,$05,$06,$07,$08,$09,$04,$05,$06,$07,$08,$09,$04,$05,$06,$07,$08,$09,$04,$05,$06,$07,$08,$09,$04,$05,$06,$07 ; row 15
        .byte   $0A,$0B,$0C,$0D,$0E,$0F,$0A,$0B,$0C,$0D,$0E,$0F,$0A,$0B,$0C,$0D,$0E,$0F,$0A,$0B,$0C,$0D,$0E,$0F,$0A,$0B,$0C,$0D,$0E,$0F,$0A,$0B,$0C,$0D,$0E,$0F,$0A,$0B,$0C,$0D ; row 16
        .byte   $10,$11,$12,$13,$14,$15,$10,$11,$12,$13,$14,$15,$10,$11,$12,$13,$14,$15,$10,$11,$12,$13,$14,$15,$10,$11,$12,$13,$14,$15,$10,$11,$12,$13,$14,$15,$10,$11,$12,$13 ; row 17
        .byte   $FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF ; row 18
        .byte   $FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF ; row 19
        .byte   $FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF ; row 20
        .byte   $FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF ; row 21
        .byte   $FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF ; row 22
        .byte   $FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF ; row 23
        .byte   $FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF ; row 24

; Helper macros for level lookup
; LEVEL_COLS .equ 40
; LEVEL_ROWS .equ 25
; LEVEL_START_ROW .equ 0
; To get tile at (col, row): LEVEL_MAP + row*LEVEL_COLS + col

; ── BAGC3 tile char data (32 chars) ──────────────
BAGC3_TILE_CHARS:
        .byte   $B7,$FF,$FF,$FF,$FF,$01,$FE,$FB,$DB,$00 ; char $10 STONE_WALL_10
        .byte   $FF,$FF,$FF,$FF,$FF,$6D,$FF,$FD,$EF,$00 ; char $11 STONE_WALL_11
        .byte   $FF,$FF,$FF,$FF,$FF,$00,$77,$F7,$E5,$00 ; char $12 STONE_WALL_12
        .byte   $FF,$FF,$FF,$FF,$FF,$B6,$DF,$BF,$FE,$00 ; char $13 STONE_WALL_13
        .byte   $FF,$FF,$FF,$FF,$FF,$88,$EF,$DF,$FF,$00 ; char $14 STONE_WALL_14
        .byte   $BF,$FF,$FF,$FF,$FF,$05,$F7,$EF,$6F,$00 ; char $15 STONE_WALL_15
        .byte   $00,$B6,$DF,$FF,$FF,$FF,$FF,$F6,$FB,$FF ; char $16 STONE_WALL_16
        .byte   $00,$FB,$FD,$FF,$FF,$FF,$FF,$FF,$7F,$FF ; char $17 STONE_WALL_17
        .byte   $00,$82,$45,$A7,$A7,$E7,$E7,$E7,$E7,$A7 ; char $18 STONE_WALL_18
        .byte   $00,$DB,$FF,$FF,$FF,$FE,$FF,$FF,$FF,$FF ; char $19 STONE_WALL_19
        .byte   $00,$65,$FB,$FF,$FF,$FF,$7F,$7F,$FF,$7F ; char $1A STONE_WALL_1A
        .byte   $00,$96,$7F,$FF,$FF,$FF,$F7,$B7,$ED,$FE ; char $1B STONE_WALL_1B
        .byte   $FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF ; char $1C STONE_WALL_1C
        .byte   $FF,$FF,$FF,$FF,$FF,$DF,$FF,$FF,$FF,$FF ; char $1D STONE_WALL_1D
        .byte   $A7,$67,$A7,$A6,$E5,$E6,$E7,$E7,$E7,$E7 ; char $1E STONE_WALL_1E
        .byte   $FF,$FE,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF ; char $1F STONE_WALL_1F
        .byte   $00,$00,$00,$00,$00,$00,$00,$00,$00,$00 ; char $20 (gap/unused)
        .byte   $7F,$FF,$FF,$7F,$DF,$FF,$FF,$FF,$FF,$FF ; char $21 STONE_WALL_21
        .byte   $FF,$FF,$FF,$FF,$FF,$FF,$FE,$FF,$FF,$FF ; char $22 STONE_WALL_22
        .byte   $FF,$FF,$FF,$FF,$FF,$0D,$F6,$ED,$FF,$00 ; char $23 STONE_WALL_23
        .byte   $F3,$F7,$F7,$F3,$F8,$B0,$FF,$F6,$B7,$00 ; char $24 STONE_WALL_24
        .byte   $FF,$FF,$FF,$FF,$92,$80,$7F,$FB,$FB,$00 ; char $25 STONE_WALL_25
        .byte   $B6,$FD,$E8,$F1,$47,$4D,$BF,$7D,$FD,$00 ; char $26 STONE_WALL_26
        .byte   $07,$1F,$7F,$FF,$FF,$80,$DF,$BF,$FB,$00 ; char $27 STONE_WALL_27
        .byte   $00,$36,$6F,$FF,$BF,$7F,$FF,$FF,$7F,$FF ; char $28 STONE_WALL_28
        .byte   $00,$DB,$FF,$FF,$FF,$FF,$FF,$FB,$F7,$FF ; char $29 STONE_WALL_29
        .byte   $00,$6D,$DB,$FF,$FF,$FF,$FF,$FD,$FB,$FF ; char $2A STONE_WALL_2A
        .byte   $00,$BE,$FD,$FF,$FF,$7F,$FF,$BF,$FF,$FF ; char $2B STONE_WALL_2B
        .byte   $00,$A0,$D1,$F0,$F0,$F9,$F0,$F1,$F9,$F0 ; char $2C STONE_WALL_2C
        .byte   $BF,$7F,$BF,$FF,$7F,$7F,$BF,$7F,$BF,$FF ; char $2D STONE_WALL_2D
        .byte   $DF,$BF,$DF,$DB,$F7,$FF,$FF,$FF,$FF,$FF ; char $2E STONE_WALL_2E
        .byte   $FF,$FF,$FF,$FF,$FD,$FF,$FF,$EF,$FF,$FF ; char $2F STONE_WALL_2F
        .byte   $F0,$D9,$F0,$F1,$F9,$F9,$F0,$F9,$F0,$F1 ; char $30 STONE_WALL_30
BAGC3_TILE_CHAR_COUNT .equ 33
BAGC3_TILE_SLOT_START .equ $10
BAGC3_DST_ADDR        .equ $0FA0 ; $0F00 + slot_start*10